version: 0.1
environment_variables:
  plaintext:
    CHILD_TEMPLATES: |
      cloudformation/environment-templates/vpc.yaml
      cloudformation/environment-templates/load-balancer.yaml
      cloudformation/environment-templates/database.yaml
      cloudformation/environment-templates/redis.yaml
    TEMPLATE_FILES: |
      cloudformation/environment-base.yaml
      cloudformation/environment-templates/vpc.yaml
      cloudformation/environment-templates/load-balancer.yaml
      cloudformation/environment-templates/database.yaml
      cloudformation/environment-templates/redis.yaml
phases:
  install:
    commands:
    - apt update && apt install -y jq
    - npm install jsonlint -g
  pre_build:
    commands:
    - ls -la
    - echo "Validating CFN templates"
    - |
      for cfn_template in $TEMPLATE_FILES; do
        echo "Validating CloudFormation template file $cfn_template"
        aws cloudformation validate-template --template-body file://$cfn_template
      done
  build:
    commands:
    - echo "Copying child stack templates to S3"
    - |
      for child_template in $CHILD_TEMPLATES; do
        aws s3 cp "$child_template" "s3://$TEMPLATE_BUCKET/codebuild/$child_template"
      done

    - echo "Updating template configurtion files to use the appropriate values"
    - cp cloudformation/config/prod/environment-base-params.json cloudformation/environment-base-params-prod.json
    - cp cloudformation/config/dev/environment-base-params.json cloudformation/environment-base-params-dev.json
    - |
      secret_string_escaped_json_prod=$(aws secretsmanager get-secret-value --region eu-west-1 --secret-id WixitProd | jq '.SecretString')
      secret_string_escaped_json_dev=$(aws secretsmanager get-secret-value --region eu-west-1 --secret-id WixitDev | jq '.SecretString')

      echo $secret_string_escaped_json_prod
      echo $secret_string_escaped_json_dev

      temp_prod="${secret_string_escaped_json_prod%\"}"
      temp_dev="${secret_string_escaped_json_dev%\"}"
      secret_string_json_prod="${temp_prod#\"}"
      secret_string_json_dev="${temp_dev#\"}"

      postgre_password_prod_str=$(echo $secret_string_json_prod | sed 's/\\//g' | jq .PostgreDbPassword)
      postgre_password_dev_str=$(echo $secret_string_json_dev | sed 's/\\//g' | jq .PostgreDbPassword)
      postgre_password_prod_str_temp="${postgre_password_str_prod%\"}"
      postgre_password_dev_str_temp="${postgre_password_str_dev%\"}"
      DATABASE_MASTER_PASSWORD_PROD="${postgre_password_str_temp_prod#\"}"
      DATABASE_MASTER_PASSWORD_DEV="${postgre_password_str_temp_dev#\"}"

      echo $DATABASE_MASTER_PASSWORD_PROD
      echo $DATABASE_MASTER_PASSWORD_DEV

      sed -i -e "s/DATABASE_MASTER_PASSWORD_PLACEHOLDER/$DATABASE_MASTER_PASSWORD_PROD/" cloudformation/environment-base-params-prod.json
      sed -i -e "s/DATABASE_MASTER_PASSWORD_PLACEHOLDER/$DATABASE_MASTER_PASSWORD_DEV/" cloudformation/environment-base-params-dev.json

    - sed -i -e "s/TEMPLATE_PATH_PLACEHOLDER/$TEMPLATE_BUCKET\/codebuild/" cloudformation/environment-base-params-prod.json
    - sed -i -e "s/TEMPLATE_PATH_PLACEHOLDER/$TEMPLATE_BUCKET\/codebuild/" cloudformation/environment-base-params-dev.json

    - cat  cloudformation/environment-base-params-prod.json
    - cat  cloudformation/environment-base-params-dev.json

    - aws s3 cp "cloudformation/environment-base.yaml" "s3://$TEMPLATE_BUCKET/codebuild/environment-base.yaml"
    - aws s3 cp "cloudformation/environment-base-params-prod.json" "s3://$TEMPLATE_BUCKET/codebuild/environment-base-params-prod.json"
    - aws s3 cp "cloudformation/environment-base-params-dev.json" "s3://$TEMPLATE_BUCKET/codebuild/environment-base-params-dev.json"
artifacts:
  files:
  - cloudformation/environment-base.yaml
  - cloudformation/environment-base-params-prod.json
  - cloudformation/environment-base-params-dev.json