version: 0.1
environment_variables:
  plaintext:
    CHILD_TEMPLATES: |
      cloudformation/environment-templates/vpc.yaml
      cloudformation/environment-templates/load-balancer.yaml
      cloudformation/environment-templates/database.yaml
    TEMPLATE_FILES: |
      cloudformation/environment-base.yaml
      cloudformation/environment-templates/vpc.yaml
      cloudformation/environment-templates/load-balancer.yaml
      cloudformation/environment-templates/database.yaml
phases:
  install:
    commands:
      npm install jsonlint -g
  pre_build:
    commands:
    - ls -la
    - echo "Validating CFN templates"
    - |
      for cfn_template in $TEMPLATE_FILES; do
        echo "Validating CloudFormation template file $cfn_template"
        aws cloudformation validate-template --template-body file://$cfn_template
      done
  build:
    commands:
    - echo "Copying child stack templates to S3"
    - |
      for child_template in $CHILD_TEMPLATES; do
        aws s3 cp "$child_template" "s3://$TEMPLATE_BUCKET/codebuild/$child_template"
      done
    - |
      echo "Updating template configurtion files to use the appropriate values"
      aws s3 cp "s3://wixit-core-configs/configs/prod/environment-base-params.json" "cloudformation/environment-base-params-prod.json"
      sed -i -e "s/TEMPLATE_PATH_PLACEHOLDER/$TEMPLATE_BUCKET\/codebuild/" cloudformation/environment-base-params-prod.json
      aws s3 cp "cloudformation/environment-base.yaml" "s3://$TEMPLATE_BUCKET/codebuild/environment-base.yaml"
      aws s3 cp "cloudformation/environment-base-params-prod.json" "s3://$TEMPLATE_BUCKET/codebuild/environment-base-params.json"
artifacts:
  files:
  - cloudformation/environment-base.yaml
  - cloudformation/environment-base-params-prod.json