version: 0.1
environment_variables:
  plaintext:
    CHILD_TEMPLATES: |
      cloudformation/environment-templates/vpc.yaml
      cloudformation/environment-templates/load-balancer.yaml
      cloudformation/environment-templates/database.yaml
    TEMPLATE_FILES: |
      cloudformation/environment-base.yaml
      cloudformation/environment-templates/vpc.yaml
      cloudformation/environment-templates/load-balancer.yaml
      cloudformation/environment-templates/database.yaml
phases:
  install:
    commands:
    - apt update && apt install -y jq
    - npm install jsonlint -g
  pre_build:
    commands:
    - ls -la
    - echo "Validating CFN templates"
    - |
      for cfn_template in $TEMPLATE_FILES; do
        echo "Validating CloudFormation template file $cfn_template"
        aws cloudformation validate-template --template-body file://$cfn_template
      done
  build:
    commands:
    - echo "Copying child stack templates to S3"
    - |
      for child_template in $CHILD_TEMPLATES; do
        aws s3 cp "$child_template" "s3://$TEMPLATE_BUCKET/codebuild/$child_template"
      done

    - echo "Updating template configurtion files to use the appropriate values"
    - cp cloudformation/config/prod/environment-base-params.json cloudformation/environment-base-params-prod.json
    - |
      secret_string_escaped_json=$(aws secretsmanager get-secret-value --region eu-west-1 --secret-id WixitProd | jq '.SecretString')
      temp="${secret_string_escaped_json%\"}"
      secret_string_json="${temp#\"}"
      python --version
      password_str=$(echo $secret_string_json | sed 's/\\//g' | jq .PostgreDbPassword)
      temp="${password_str%\"}"
      DATABASE_MASTER_PASSWORD="${temp#\"}"

      sed -i -e "s/DATABASE_MASTER_PASSWORD_PLACEHOLDER/$DATABASE_MASTER_PASSWORD\/codebuild/" cloudformation/environment-base-params-prod.json
      cat cloudformation/environment-base-params-prod.json

    - sed -i -e "s/TEMPLATE_PATH_PLACEHOLDER/$TEMPLATE_BUCKET\/codebuild/" cloudformation/environment-base-params-prod.json
    - cat cloudformation/environment-base-params-prod.json
    - aws s3 cp "cloudformation/environment-base.yaml" "s3://$TEMPLATE_BUCKET/codebuild/environment-base.yaml"
    - aws s3 cp "cloudformation/environment-base-params-prod.json" "s3://$TEMPLATE_BUCKET/codebuild/environment-base-params.json"
artifacts:
  files:
  - cloudformation/environment-base.yaml
  - cloudformation/environment-base-params-prod.json